channels:
- name: 한경 글로벌마켓
  corners:
  - name: 빈난새의 빈틈없이월가
    playlist_id: PLAddSCfY5PwNZXKsCxHCuIleQacL4VAB9
  max_results: 3
  active: true
  channel_id: UCWskYkV4c4S9D__rsfOl2JA
- name: 매경 월가월부
  corners:
  - name: 홍장원의 불앤베어
    playlist_id: PLF5Fz9qlNg7DPSdYkUSDWc8dLR9oiSab_
  max_results: 3
  active: true
  channel_id: UCIipmgxpUxDmPP-ma3Ahvbw
- name: 교양이를 부탁해
  corners:
  - name: 교양이 HOT
    playlist_id: PLPtP6TAuOHakSa8g_3bIbUy70HDLEoPbK
  max_results: 3
  active: true
  channel_id: UChY8VUjXv0aA7RF9hDQ0ISg
- name: 전인구경제연구소
  corners:
  - name: 주식
    playlist_id: PLpezlh5x80cu8KTXJQ7CSqr8HwLs6cL9x
  max_results: 3
  active: true
  channel_id: UCznImSIaxZR7fdLCICLdgaQ
